import type { Metadata } from "next";
import { Geist, Geist_Mono, Shantell_Sans, Inria_Serif } from "next/font/google";
import "./globals.css";
import { BottomNav } from "./components/BottomNav";
import Streaks from "./components/Streaks";
import { StreakRefreshProvider } from "./context/StreakRefreshContext";
import { NoteProvider } from "./context/NoteContex";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const shantell = Shantell_Sans({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700'],
  variable: '--font-shantell',
  display: 'swap',
});

const inria = Inria_Serif({
  subsets: ['latin'],
  weight: ['300'],
  style: ['italic'],
  variable: '--font-inria',
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable} ${shantell.variable} ${inria.variable} antialiased`}>


      <body className=""
              style={{
                backgroundImage: `
                  linear-gradient(to right, #262626 1px, transparent 1px),
                  linear-gradient(to bottom, #262626 1px, transparent 1px)
                `,
                backgroundSize: "40px 40px",
              }}>
        <NoteProvider>
        <StreakRefreshProvider>

          <div className={` flex justify-between w-full mx-auto`}>


          </div>

          <Streaks />
          {children}
          <BottomNav />

        </StreakRefreshProvider>
        </NoteProvider>
      </body>
    </html>
  );
}
